server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/wishlistdb
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: dev

logging:
  level:
    org.springframework.web: INFO